url = https://www.saucedemo.com/
browser = chrome

#mysql
db_url_ms = jdbc:mysql://localhost:3306/
username = root
password = root

#postgres
username_pg =
password_pg =

#mongo
username_mongo =
password_mongo =

# JIRA
automatic_Issue_Creation_In_JIRA = OFF
jiraURL = 
jiraUserName = 
jiraSecretKey = 

#retry
retryCount = 1
